#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Fri Jul 10 02:29:17 GMT 2026
android.nonTransitiveRClass=true
kotlin.daemon.jvm.options=-Xmx2048m
systemProp.user.language=en
systemProp.user.country=US
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.aapt2FromMavenOverride=/data/user/0/com.tom.rv2ide/files/home/.androidide/aapt2
